[project]
name = "mauro"
description = "Test package"
authors = ["Mauro Silberberg <maurosilber@gmail.com>"]
channels = ["https://fast.prefix.dev/conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.13"

[pypi-dependencies]
mauro = { path = ".", editable = false }

[environments]
lint = { features = ["lint"], no-default-feature = true }
build = { features = ["build"], no-default-feature = true }
test = { features = ["test"], solve-group = "default" }
test-py313 = ["test", "py313"]

[feature.lint.dependencies]
pre-commit = "*"
pre-commit-hooks = "*"
taplo = "*"
ruff = "*"
mdformat = "*"
mdformat-ruff = "*"

[feature.lint.tasks]
pre-commit-install = "pre-commit install"
lint = "pre-commit run"

[feature.build.dependencies]
uv = "*"

[feature.build.tasks]
build = "uv build"
publish = "uv publish"

[feature.test.dependencies]
pytest = "*"

[feature.test.tasks]
test = "pytest --doctest-modules"

[feature.py313.dependencies]
python = "3.13.*"
